package com.example.bookstore.model;
// Generated Nov 22, 2019, 1:47:53 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Author generated by hbm2java
 */
@Entity
@Table(name = "author", schema = "public")
public class Author implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 6114824904101865051L;
	private long id;
	private String firstName;
	private String lastName;
	private Set<Books> bookses = new HashSet<Books>(0);

	public Author() {
	}

	public Author(long id) {
		this.id = id;
	}

	public Author(long id, String firstName, String lastName, Set<Books> bookses) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
		this.bookses = bookses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "first_name")
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name")
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@OneToMany(mappedBy = "author")
	@JsonIgnore
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
