package com.example.bookstore.model;
// Generated Nov 22, 2019, 1:47:53 PM by Hibernate Tools 4.3.5.Final

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Books generated by hbm2java
 */
@Entity
@Table(name = "books", schema = "public")
public class Books implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 259025484748000915L;
	private long bookId;
	private Author author;
	private Category category;
	private Publisher publisher;
	private String description;
	private Date releaseDate;
	private String title;
	private Double price;

	public Books() {
	}

	public Books(long bookId) {
		this.bookId = bookId;
	}

	public Books(long bookId, Author author, Category category, Publisher publisher, String description,
			Date releaseDate, String title, Double price) {
		this.bookId = bookId;
		this.author = author;
		this.category = category;
		this.publisher = publisher;
		this.description = description;
		this.releaseDate = releaseDate;
		this.title = title;
		this.price = price;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "book_id", unique = true, nullable = false)
	public long getBookId() {
		return this.bookId;
	}

	public void setBookId(long bookId) {
		this.bookId = bookId;
	}

	@ManyToOne()
	@JoinColumn(name = "author_id")
	public Author getAuthor() {
		return this.author;
	}

	public void setAuthor(Author author) {
		this.author = author;
	}

	@ManyToOne()
	@JoinColumn(name = "category_id")
	public Category getCategory() {
		return this.category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	@ManyToOne()
	@JoinColumn(name = "publisher_id")
	public Publisher getPublisher() {
		return this.publisher;
	}

	public void setPublisher(Publisher publisher) {
		this.publisher = publisher;
	}

	@Column(name = "description")
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "release_date", length = 29)
	public Date getReleaseDate() {
		return this.releaseDate;
	}

	public void setReleaseDate(Date releaseDate) {
		this.releaseDate = releaseDate;
	}

	@Column(name = "title")
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "price", precision = 17, scale = 17)
	public Double getPrice() {
		return this.price;
	}

	public void setPrice(Double price) {
		this.price = price;
	}

}
