package com.example.bookstore.model;
// Generated Nov 22, 2019, 1:47:53 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name = "category", schema = "public")
public class Category implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 5526824382967811469L;
	private long id;
	private String categoryDescription;
	private String categoryName;
	private Set<Books> bookses = new HashSet<Books>(0);

	public Category() {
	}

	public Category(long id, String categoryDescription, String categoryName) {
		this.id = id;
		this.categoryDescription = categoryDescription;
		this.categoryName = categoryName;
	}

	public Category(long id, String categoryDescription, String categoryName, Set<Books> bookses) {
		this.id = id;
		this.categoryDescription = categoryDescription;
		this.categoryName = categoryName;
		this.bookses = bookses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "category_description", nullable = false)
	public String getCategoryDescription() {
		return this.categoryDescription;
	}

	public void setCategoryDescription(String categoryDescription) {
		this.categoryDescription = categoryDescription;
	}

	@Column(name = "category_name", nullable = false)
	public String getCategoryName() {
		return this.categoryName;
	}

	public void setCategoryName(String categoryName) {
		this.categoryName = categoryName;
	}

	@OneToMany(mappedBy = "category")
	@JsonIgnore
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
