package com.example.bookstore.model;
// Generated Nov 22, 2019, 1:47:53 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Grade generated by hbm2java
 */
@Entity
@Table(name = "grade", schema = "public")
public class Grade implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = -4606847280344133877L;
	private long id;
	private double bestProduction;
	private String quality;
	private Set<Publisher> publishers = new HashSet<Publisher>(0);

	public Grade() {
	}

	public Grade(long id, double bestProduction, String quality) {
		this.id = id;
		this.bestProduction = bestProduction;
		this.quality = quality;
	}

	public Grade(long id, double bestProduction, String quality, Set<Publisher> publishers) {
		this.id = id;
		this.bestProduction = bestProduction;
		this.quality = quality;
		this.publishers = publishers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "best_production", nullable = false, precision = 17, scale = 17)
	public double getBestProduction() {
		return this.bestProduction;
	}

	public void setBestProduction(double bestProduction) {
		this.bestProduction = bestProduction;
	}

	@Column(name = "quality", nullable = false)
	public String getQuality() {
		return this.quality;
	}

	public void setQuality(String quality) {
		this.quality = quality;
	}

	@OneToMany(mappedBy = "grade")
	@JsonIgnore
	public Set<Publisher> getPublishers() {
		return this.publishers;
	}

	public void setPublishers(Set<Publisher> publishers) {
		this.publishers = publishers;
	}

}
