package com.example.bookstore.model;
// Generated Nov 22, 2019, 1:47:53 PM by Hibernate Tools 4.3.5.Final

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**N
 * Publisher generated by hbm2java
 */
@Entity
@Table(name = "publisher", schema = "public")
public class Publisher implements java.io.Serializable {

	/**
	 *
	 */
	private static final long serialVersionUID = 8815598396747022790L;
	private long id;
	private Grade grade;
	private String country;
	private String publisherName;
	private Set<Books> bookses = new HashSet<Books>(0);

	public Publisher() {
	}

	public Publisher(long id, String country, String publisherName) {
		this.id = id;
		this.country = country;
		this.publisherName = publisherName;
	}

	public Publisher(long id, Grade grade, String country, String publisherName, Set<Books> bookses) {
		this.id = id;
		this.grade = grade;
		this.country = country;
		this.publisherName = publisherName;
		this.bookses = bookses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@ManyToOne()
	@JoinColumn(name = "grade_id")
	public Grade getGrade() {
		return this.grade;
	}

	public void setGrade(Grade grade) {
		this.grade = grade;
	}

	@Column(name = "country", nullable = false)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@Column(name = "publisher_name", nullable = false)
	public String getPublisherName() {
		return this.publisherName;
	}

	public void setPublisherName(String publisherName) {
		this.publisherName = publisherName;
	}

	@OneToMany(mappedBy = "publisher")
	@JsonIgnore
	public Set<Books> getBookses() {
		return this.bookses;
	}

	public void setBookses(Set<Books> bookses) {
		this.bookses = bookses;
	}

}
